apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-proxy-addon-agent-impersonator
rules:
{{- $enableHubTokenAuthentication := eq (include "cluster-proxy-common.hubTokenAuthenticationEnabled" .) "true" }}
{{- $enableOIDCAuthentication := eq (include "cluster-proxy-addon.oidcAuthenticationEnabled" .) "true" }}
{{- if or $enableHubTokenAuthentication $enableOIDCAuthentication }}
- apiGroups: [""]
  resources: ["users", "groups"]
  verbs: ["impersonate"]
{{- end }}
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
